### ISSUE TITLE
ci: containerize linux deps

### ISSUE THREAD

**Issue by junr03** [envoyproxy/envoy-mobile#100]
Currently linux deps are installed on every linux CI run. We can build an image and host it on dockerhub. The wrinkle here is that the Azure linux agent gives us a bunch of stuff for free -- including the android sdk and ndk -- so we will have to bake that into the image as well.

**Comment by jpsim** [comment]
This is mostly done since we use the envoy-build-ubuntu Docker image.

There's a single CI job that installs some Android build dependencies via this script: https://github.com/envoyproxy/envoy/blob/main/mobile/ci/linux_ci_setup.sh

A recent run of that CI job shows that this setup took 68 seconds to run so this isn't a significant concern: https://github.com/envoyproxy/envoy/actions/runs/3631327773/jobs/6125815249

**Comment by jpsim** [comment]
Attempting to do this anyway: https://github.com/envoyproxy/envoy-build-tools/pull/188
