### ISSUE TITLE
Envoy-Mobile sends  "x-" headers

### ISSUE THREAD

**Issue by carloseltuerto** [envoyproxy/envoy-mobile#1557]
Envoy Mobile seems to systematically send these two request headers:

```
x-envoy-mobile-cluster: base_clear_alt
x-forwarded-proto: https
```

This has been noticed with HTTP1. It is not known it this happens for HTTP2 also.

**Comment by alyssawilk** [comment]
XFP can hopefully be removed but it's going to take some time for safe migration (6 months so far, probably another 3-6 to go: https://github.com/envoyproxy/envoy/issues/14587)

cluster_header: x-envoy-mobile-cluster is added here:
https://github.com/envoyproxy/envoy-mobile/blob/main/library/common/config/config.cc#L163

@junr03 @buildbreaker I assume you folks value having that sent from client to server?  If it's Ok to remove I can do so, otherwise should we kick off a way to template that config file so cronvoy can have different defaults than E-M?

**Comment by alyssawilk** [comment]
Ok charles, I think I've fixed this one but I'm not sure which cronvoy test it was so throwing it over to you for verification
BTW if you want to start tagging example tests when you file issues I can look at updating tests when I update config.  Your call!

**Comment by carloseltuerto** [comment]
Unfortunately, not yet. This is what the MockWebServer gets:

```
User-Agent: io.envoyproxy.envoymobile.test/0 (Linux; U; Android 8.1.0; en_US; robolectric; Build/OSM2.180218.001; Cronet/99.0.4512.7)
x-envoy-mobile-cluster: base_clear
x-forwarded-proto: https
accept-encoding: gzip
```

And there is something interesting:  ```x-envoy-mobile-cluster:``` and ```x-forwarded-proto:``` are only being sent on the wire when there is an ```accept-encoding:``` in the request

**Comment by alyssawilk** [comment]
ok, mind checking again when you have a few?

**Comment by alyssawilk** [comment]
confirmed fixed, thanks @carloseltuerto
