### ISSUE TITLE
[CI] Update to Xcode 14

### ISSUE THREAD

**Issue by jpsim** [envoyproxy/envoy-mobile#2544]
This is now the latest stable Xcode release and we should update to it in order to compile against the latest iOS SDK.

* Version: 14.0 (14A309)
* Release Notes: https://developer.apple.com/documentation/xcode-release-notes/xcode-14-release-notes
* Download: https://download.developer.apple.com/Developer_Tools/Xcode_14/Xcode_14.xip

Will require EngFlow to update their executors just as was done for #1997 and #2100. This version of Xcode also requires macOS 12.5 to run, so an OS update to the workers may also be needed.

cc @lfpino @Yannic

**Comment by Yannic** [comment]
Starting the process on our side. ETA later this week.

**Comment by Yannic** [comment]
FYI, we tried to update today but it seems to have caused problems downstream: https://engflow.slack.com/archives/C02QMNG92A3/p1663268271326349 

Investigating tomorrow.

**Comment by jpsim** [comment]
@Yannic how's the update process going? Is there anything I can do to help?

**Comment by Yannic** [comment]
We deployed the change to the cluster but had to revert because it was [causing other issues](https://engflow.slack.com/archives/C02QMNG92A3/p1663268271326349) (missing python3?). We need to investigate whether Apple changed anything in Xcode (I do see a new Xcode-related download on developer.apply.com).

Do you know what's up with that?

**Comment by keith** [comment]
I don't think anything from bazel relies on py2 at this point because of this, and since it's long deprecated, I'm not in the engflow slack but is it an engflow thing hitting the issue?
